### PR TITLE
Add Contact page

### LINKED ISSUE #4: Create a unified contact page
I've heard more than once that it's hard to figure out how to get in touch with the club. I think there should be a "Contact" page that includes:
- Embedded webchat, or at least a link to webchat (maybe a link to mgius' old XChat instructions too)
- Contact information (name/email) for current officers
- Link to lists (announcement/discussion/execboard), once we figure those out again

### PR DESCRIPTION
**Pull request by coyotebush**
Fixes #4. Work in progress.

@jmcgover @sarcasticsimba what officer contact info makes sense to include? email, twitter, github, photo, major/year, bio ...?

Compare http://calpolyieee.org/officers/ or the minimal http://cpgd.org/ http://thewhitehat.club/

### CODE REVIEW

**Comment by jmcgover** [comment]
Even more minimal: http://w6bhz.org/content/members

Yeah: 
- email
- photo
- major/year
- bio (like in the IEEE thing maybe)

Maybe:
- linux flavor specialty (like on the weekly FYM schedule on the site)
- irc handle (so they know who's who in the chat)
- twitter (I'm very active, but also occasionally profane)
- github

**Comment by viplup** [comment]
Those seem to cover the bases. I like what IEEE does: the "who we are" portion is mandatory, and is followed by optional icons (e.g.—email, facebook)

We could do something similar, except bundle our IRC nicks with our full name.

**Comment by coyotebush** [comment]
The pre-2007 website, as a point of curiosity, had [a member directory](https://web.archive.org/web/20070626061041/http://www.cplug.org/profiles) with info on each member's use of Linux.

**Comment by viplup** [comment]
That's actually a really neat idea! I also like their style (seriously). Aside: it's so cool to see how crowded FYM was.

**Comment by coyotebush** [comment]
Not completely satisfied with this myself, but comments on the content and markup welcome. Maybe we should just use a row layout closer to IEEE's, especially if we want longer bios.

officers

**Comment by coyotebush** [comment]
There really ought to be a link to the Facebook group in the first paragraph, too.
And maybe I'll group `contact`, `irc` and `mailing-list` into a directory.

**Comment by jmcgover** [comment]
Wow that looks super awesome! I really like it. Everything looks really clean and the monospace font on the user handle is great. 

The row layout should be fine, if you think that'll fit better. I can't think of a bio any longer than what you have. 

I like the structure in the old site's profiles page, but I'm not sure that we need it to be that complex. I can't see the images anymore, but I assume they're the logo of the distro and I thought that was really cool. 

Maybe we can make a second row of icons underneath the social media icons of the distros we're familiar with and prefer --- where the icon links to the distro's main webpage. It could shorten our bio's, link students to more info about the distro, and get them familiar with the flavors and their logos. Adding an extra row might clutter it and be too many rows, though. I'm not sure.

**Comment by jmcgover** [comment]
Now that I think about it, a whole new row might not be necessary if we all only list one distro. I spend time in a lot of different Linux/Unix environments, so I'd put Arch and OSX and maybe Debian/Ubuntu/Raspian. But I think most people would just list one.

So, maybe having our distro of choice in the bio is fine and we don't need that extra row.

**Comment by coyotebush** [comment]
I think leaving the preferred OS info in prose is nice so we have the flexibility to go into more detail wherever we want. Feel free to mention two or three.

**Comment by coyotebush** [comment]
Over to you two to fill out your own sections!

**Comment by coyotebush** [comment]
I'm going to :shipit: but feel free to make followup tweaks on master.

**Pull request merged**
