### PR TITLE
Set the site title properly.

### LINKED ISSUE #7: Fix the title
`<title>CPLUG - </title>`

### PR DESCRIPTION
**Pull request by brotatos**
Add description to _config.yml.

_layouts/default.html was relying on
site.description to set the title fully.

Fixes #7.

### CODE REVIEW

**Comment by coyotebush** [comment]
Can we get proper titles on individual pages/posts too, though?

**Comment by brotatos** [comment]
Do you want their title to be the main header of the page/post instead of "CPLUG - Cal Poly..."?

**Comment by coyotebush** [comment]
Yes please. See: the current WordPress site.

**Comment by brotatos** [comment]
Done.

**Pull request merged**
